- src/sklearn_knn/_base.py
- src/sklearn_knn/_euclidean.py
- src/sklearn_knn/_gnn.py
- src/sklearn_knn/_mahalanobis.py
- src/sklearn_knn/_raw.py
- tests/test_estimators.py
- tests/test_port.py
This would close #13 by making all estimators subclass `KNeighborsRegressor` instead of `KNeighborsClassifier`, allowing us to fit and predict continuous multioutput data. It also removes the `kneighbor_ids` method following the discussion in #2, but leaves the (renamed) `IDNeighborsRegressor` in place while we figure out whether we need that. 
All of the tests against neighbor IDs have been temporarily disabled. If we end up supporting dataframe indices, we'll probably want to modify to test for those. If not, we can probably get rid of them unless there's a reason to test array indices (which I assume would require remaking the neighbor csvs).
Lastly, this adds some very basic tests to make sure all the estimators can `fit` and `predict` with continuous multioutput data. I'm assuming …
> Subclass estimators from KNeighborsRegressor

- src/sknnr/_base.py
- src/sknnr/_euclidean.py
- src/sknnr/_gnn.py
- src/sknnr/_mahalanobis.py
- src/sknnr/transformers/__init__.py
- src/sknnr/transformers/_base.py
- src/sknnr/transformers/_cca_transformer.py
- src/sknnr/transformers/_mahalanobis_transformer.py
- src/sknnr/transformers/_standard_scaler_dof.py
- tests/test_estimators.py
This addresses issues raised in both #6 and #15.
- `MyStandardScaler` renamed to `StandardScalerWithDOF`
- Moved into `transformers` directory
- Cast dataframe to array before setting `scale_` attribute
- Add new test to check dataframe compliance
> Rename MyStandardScaler and fix to work with dataframes

- src/sknnr/_base.py
Resolves #23.  The discussion there gives good background and an explanation of this fix.
> Remove TransformedKNeighborsMixin.predict to avoid double transformation

- pyproject.toml
- src/sknnr/_base.py
- src/sknnr/transformers/_base.py
- src/sknnr/transformers/_cca_transformer.py
- src/sknnr/transformers/_ccora_transformer.py
- src/sknnr/transformers/_mahalanobis_transformer.py
- tests/test_estimators.py
- tests/test_transformers.py
This PR closes #20 by making our transformers compatible with the [set_output API](https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_set_output.html), allowing them to output dataframes based on configuration.
@grovduck, this ballooned into a pretty big PR, so I could definitely use a second set of eyes to make sure I didn't go off the rails anywhere! I tried to lay out the details and reasoning of the big changes below. Most of these were discussed in the issue, but a few things came up during implementation. Happy to discuss anything!
This method is [automatically available](https://github.com/scikit-learn/scikit-learn/blob/689efe2f25356aa674bd0090f44b0914aae4d3a3/sklearn/utils/_set_output.py#L213) for all `BaseEstimator` subclasses via the `_SetOutputMixin` once they …
> Dataframe compatibility for transformers

- src/sknnr/_base.py
- src/sknnr/transformers/_base.py
- tests/test_estimators.py
- tests/test_transformers.py
This closes #35 and simplifies feature validation. [This comment](https://github.com/lemma-osu/scikit-learn-knn-regression/issues/35#issuecomment-1583088921) and [this commit](https://github.com/lemma-osu/scikit-learn-knn-regression/commit/b213566d5270ce34764eddba6faa6383e3a5381e) go into more depth on the changes here, but the bullet points are:
1. Remove `set_temp_output` because we no longer need transformers to pass dataframes into transformed estimators since we can get feature names from the transformer.
2. Remove the warning logic from `TransformedKNeighborsMixin._check_feature_names`. That is now handled by calling `transform_._validate_data`. This method now just serves to override the internal check that would incorrectly fail when our estimator is fit with transformed features …
> Fix broken warning and reduce complexity of feature validation #35

- src/sknnr/_base.py
- src/sknnr/transformers/_cca_transformer.py
- src/sknnr/transformers/_ccora_transformer.py
For `CCATransformer` and `CCorATransformer`, store matrices from ordination as estimator attributes within `fit` method.  Previously, we were calling properties from `CCA` and `CCorA` (respectively) that were recomputing expensive operations.  Because the matrix projectors don't change once fit, it's more efficient to store as estimator attributes.
Also, remove redundant call to `_validate_data` in `TransformedKNeighborsMixin._apply_transform` as the transformers are now responsible for that call.
> Store repeatedly used variables as estimator attributes #47

- src/sknnr/_base.py
- src/sknnr/transformers/_cca_transformer.py
- tests/test_estimators.py
This resolves #55 by only storing the `dataframe_index_in_` if it's array-like, and updates `test_estimators_support_dataframe_indexes` to confirm that the `list.index` method isn't accidentally stored like it previously was.
While testing this I noticed a small bug that prevented fitting `CCATransformer` with a `y: list` due to the dimensionality check. Just changing the order of casting and checking shape solved that, so I included it here as a quick fix.
> Only store array-like `dataframe_index_in_` and fix `CCA` compability with `list`

- README.md
Quick fix for the links to the docs in README (for future reference, we need to link to `https://sknnr.readthedocs.io/en/latest/***`).
> Fix README doc links

- .github/workflows/ci.yaml
- README.md
The biggest change is adding `3.12` to our CI now that it's officially out (we're passing!), but I also bumped a few actions to the latest versions and added a docs badge to the readme while I was at it. @grovduck I hope you don't mind the combined PR!
> Add `3.12` to CI

- README.md
- docs/mkdocs.yml
- docs/pages/installation.md
- pyproject.toml
- src/sknnr/__about__.py
Closes #61 by updating all references from `scikit-learn-knn-regression` to `sknnr`. Also preps for the `0.1.0-alpha` release by updating install instructions and the package version.
> Rename package to sknnr and prep for alpha release

- .pre-commit-config.yaml
- docs/pages/contributing.md
- pyproject.toml
- src/sknnr/datasets/_base.py
Per changes made in [`sknnr-spatial`](https://github.com/lemma-osu/sknnr-spatial/commit/1da7ceaf4af1384228a704859d126cc08855752b), update the pre-commit versions to latest versions. 
- `ruff: v0.3.2`
- `mypy: v1.9.0`
In addition, remove the use of `black` as a pre-commit hook and instead rely on `ruff-format`.  Also, update `contributing.md` to show command use with `hatch` and to align it with the contributing guide for `sknnr-spatial`.
> Update pre-commit versions and contributing doc

- .github/workflows/ci.yaml
- tests/test_port.py
As part of using the [Array API](https://github.com/scikit-learn/scikit-learn/pull/27904) for `r2_score`, the return value of `r2_score` is now cast explicitly as a `float` rather than `np.float64` when it is a scalar value.
From [this doc](https://github.com/scikit-learn/scikit-learn/blob/c44457af96a924683b6a65bd3fd6c285043bdec6/doc/modules/array_api.rst?plain=1#L138-L152):
> Note however that scoring functions that return scalar values return Python scalars (typically a `float` instance) instead of an array scalar value.
In `test_port.test_score_independent`, we were calling `r2_score` using the default `multioutput="uniform_average"` which was returning a single `np.float64`.  We were then mistakenly calling `.mean()` on this value which had not previously thrown an error because it …
> Fix `r2_score` port test

- src/sknnr/datasets/__init__.py
- src/sknnr/datasets/_base.py
- tests/test_datasets.py
Closes #68 by adding `load_csv_data` and `load_dataset_from_csv_filenames` to the public API.  `data_module` is now passed as a keyword argument to both functions and defaults to `sknnr.datasets.data`.
- `data_module` in both functions can be passed as either a string (e.g. "sknnr.datasets.data") or as a module object
- Rudimentary tests on `load_csv_data`
> Expose functions from `datasets` module in public API

- src/sknnr/__about__.py
Overwrites #71 by switching from the semver-compliant `0.1.0-alpha.1` to the [PEP 440-compliant](https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers) `0.1.0a1` version specifier. I had hoped to stick with semver, but following PEP440 is enforced by PyPI, and it's probably best to keep our package version and tags consistent with the PyPI releases.
> Switch to PEP440 compliant alpha tag

- docs/pages/contributing.md
As pointed out by @grovduck, `hatch version` supports release types other than major/minor/patch.
> Update `hatch version` guide

- src/sknnr/_base.py
- src/sknnr/_gnn.py
- src/sknnr/_msn.py
- tests/test_estimators.py
This would close #74 by explicitly specifying all the inherited `__init__` parameters for `MSNRegressor` and `GNNRegressor` via the new `OrdinationKNeighborsRegressor` abstract base class, so that they can be used in a grid search. I also added a basic test to run `GridSearchCV` on all estimators.
@grovduck, while I was adding the init params, I figured I might as well write up docstrings for those estimators as well. I copied directly from `KNeighborsRegressor` for all the shared parameters and attributes, but had to wing it a little bit for the specifics. Could you give those a look and edit as needed? Also, should we add some references or any more implementation info?
~I also considered making a shared mixin class to avoid the duplicated `__init__` method - something like …
> Specify all `__init__` params for MSN and GNN

- .github/workflows/ci.yaml
- .gitignore
- docs/pages/installation.md
- pyproject.toml
- src/sknnr/datasets/_base.py
- tests/datasets.py
- tests/test_datasets.py
Raises the minimum supported Python to 3.9, in anticipation of end-of-life for 3.8 in a couple months.
That allowed us to remove an internal compatibility function and use the "new" parenthesized `with` block. Unrelated, I removed the `target-version` specifier to allow Ruff to infer it from `requires-python` and added the `dist` build directory to `.gitignore`.
> Drop Python 3.8 support

- pyproject.toml
Closes #64 by adding a `test_matrix` Hatch env for testing across Python versions (e.g. `hatch run test_matrix:all`).
@grovduck, I just copied the config from `synthetic-knn` to keep everything consistent, and will duplicate this in `sknnr-spatial` next.
> Add Hatch script for local Python matrix tests

- pyproject.toml
- src/sknnr/_base.py
- src/sknnr/_gnn.py
- src/sknnr/_msn.py
- src/sknnr/transformers/_base.py
- src/sknnr/transformers/_cca_transformer.py
- src/sknnr/transformers/_ccora_transformer.py
- src/sknnr/transformers/_mahalanobis_transformer.py
- tests/test_estimators.py
- tests/test_transformers.py
Closes #78 by introducing compatibility fixes for [breaking changes in sklearn >= 1.6](https://scikit-learn.org/1.6/whats_new/v1.6.html#version-1-6-0), described below.
As far as our downstream packages, if anything relied on `feature_names_in_` or `n_features_in_` they would need to be updated, but I did a quick search and didn't see either show up in the code of `sknnr-spatial`, `synthetic-knn`, or `gee-knn-python`. 
Instead of marking our xfailing estimator checks in the estimator tags, they're now passed as arguments to [`parametrize_with_checks`](https://scikit-learn.org/1.6/modules/generated/sklearn.utils.estimator_checks.parametrize_with_checks.html#sklearn.utils.estimator_checks.parametrize_with_checks). I'm very happy with this change since it got a lot of testing details out of …
> Scikit-learn 1.6 compatibility

- pyproject.toml
- src/sknnr/_base.py
- tests/test_estimators.py
- tests/test_transformers.py
There were a few more breaking changes between `sklearn==1.6.0rc1` and `1.6.0` (now released) which this resolves:
1. `multi_label` is no longer an attribute of `RegressorTags` (I've tried to find where this was changed to figure out the rationale, but didn't have any luck. Maybe it was never implemented but it just wasn't being checked before?).
2. `check_positive_only_tag_during_fit` was added, which uses 1D data that breaks CCA.
> Tag fixes for `sklearn==1.6.0`

- src/sknnr/_base.py
- src/sknnr/transformers/_cca_transformer.py
- src/sknnr/transformers/_ccora_transformer.py
Closes #82 and #83
- CCA now correctly requires positive targets
- CCorA now correctly requires targets
- All estimators (other than `RawKNNRegressor`) now explicitly prohibit sparse data. This is a temporary measure to fix failing checks. A closer investigation of sparse support is needed.
- The addition of `target_tags.required` to CCorA triggered an estimator check `check_requires_y_none` which looks for an expected error message when passed `y=None`. That error is now correctly raised by passing y into `_validate_data`. This removed the need to separately check the y array. Note that we don't mutate `X` with the validation check as this will strip feature names that must be passed to `StandardScalerWithDOF`.
@grovduck, please check and confirm that I covered all the tag changes we …
> Finalize estimator tags and fix sparse test failure

- .pre-commit-config.yaml
- tests/datasets.py
- tests/test_estimators.py
As with lemma-osu/sklearn-raster#52, this PR updates pre-commit hooks for `sknnr` and fixes [PT001](https://docs.astral.sh/ruff/rules/pytest-fixture-incorrect-parentheses-style/) issues.
> Update precommit hooks to latest

- .github/workflows/ci.yaml
- pyproject.toml
Closes #94 by adding a test dependency on `pytest-xdist` and parallelizing CI tests. CI uses all 4 available threads (per [Github docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)), which decreased overall CI time from about 3.5 minutes to 2.25, based on just one run.
Local tests are still serial by default but can be run in parallel with (using 8 threads):
```
hatch run test:all -n 8
```
@grovduck, we could parallelize locally by default (i.e. `hatch run test:all` would always use `-n auto`), but I don't have strong feelings either way. As you mentioned in #94, using `auto` adds some additional overhead so we might always end up overriding it manually …
> Run CI tests in parallel

- src/sknnr/transformers/_rfnode_transformer.py
- src/sknnr/transformers/_tree_node_transformer.py
- tests/test_transformers.py
This PR introduces a base class for transformers that capture tree node IDs during `transform`.  Currently, this is only `RFNodeTransformer`, but #96 proposes other transformers with nearly duplicate needed functionality (gradient boosting and histogram-based gradient boosting).  This represents an incremental step to introducing those transformers and their accompanying NN-based estimators by doing the following:
- Creating a new abstract `TreeNodeTransformer` class that implements `transform` and `fit_transform`, but requires subclasses to implement `fit`.  This is because each specialized transformer will have estimator-specific keyword arguments and base forest types (e.g. `RandomForestClassifier` and `RandomForestRegressor`).  However, this class implements the method `_fit` which …
> Use generic `TreeNodeTransformer` for forest-based node ID transformers
